{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "teyvat-takeout.fullname" . }}-mongodb
  labels:
    {{- include "teyvat-takeout.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
    tier: database
spec:
  serviceName: {{ include "teyvat-takeout.fullname" . }}-mongodb-service
  replicas: 1
  selector:
    matchLabels:
      {{- include "teyvat-takeout.mongodb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "teyvat-takeout.mongodb.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mongodb.service.port }}
              name: mongo
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
          {{- with .Values.mongodb.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  {{- if .Values.mongodb.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: mongodb-storage
      spec:
        accessModes:
          {{- toYaml .Values.mongodb.persistence.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.mongodb.persistence.size }}
  {{- end }}
{{- end }}
